language: ruby
rvm: 2.2.7
sudo: false
matrix:
  include:
    - rvm: 2.2.8
    - rvm: 2.3.5
    - rvm: 2.4.2
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

os:
  - linux

before_install:
  - gem install bundler

script:
  - gem list -l
  - bundle exec rake compile
  - bundle exec rake
  - bundle exec codeclimate-test-reporter
  - gem build ./midori_http_parser.gemspec

notifications:
  email: false
