language: ruby
rvm: 2.1.0
sudo: false
matrix:
  include:
    - rvm: 2.2.6
    - rvm: 2.3.3
    - rvm: 2.4.0
    - rvm: ruby-head
    - rvm: jruby-9.0.4.0
      jdk: oraclejdk7
    - rvm: jruby-9.0.4.0
      jdk: oraclejdk8
    - rvm: jruby-9.0.4.0
      jdk: openjdk7
    - rvm: jruby-head
      jdk: oraclejdk7
    - rvm: jruby-head
      jdk: oraclejdk8
    - rvm: jruby-head
      jdk: openjdk7
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head

os:
  - linux

before_install:
  - gem install bundler

notifications:
  email: false
